version: '3'
services:
  mongodb:
    image: 'mongo'
    ports:
      # local port:container port, just to access the API from localhost
      - "27017:27017"
  music-corp-app:
    build: .
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
    ports:
      # local port:container port, just to access the API from localhost
      - "4001:8080"